apiVersion: v1
kind: Pod
metadata:
  name: test-private
spec:
  containers:
  - name: test-private
    image: index.docker.io/aisuko/test-k8s-private:3.7
    imagePullPolicy: Always
  imagePullSecrets:
  - name: aisuko-regis