apiVersion: skaffold/v1beta10
kind: Config

build: {}
deploy:
  kubectl:
    manifests:
      - k8s-*.yaml
      - service-*.yaml

profiles:
  - name: deploy-helm
    deploy:
      helm:
        releases:
          - name: skaff
            chartPath: skaff
            namespace: skaffo
            wait: false
            recreatePods: true
            skipBuildDependencies: false
            useHelmSecrets: false
            packaged:
              version: 0.2.0
              appVersion: "2.0"
            valuesFiles: [./values.yaml]
            

  - name: deploy-kustomize
    deploy:
      kustomize:
        path: .
        flags:
          global: []
          apply: []
          delete: []
