apiVersion: skaffold/v1beta11
kind: Config

build: {}
deploy:
  kubectl:
    manifests:
      - k8s-*.yaml
      # - service-*.yaml

profiles:
  - name: build-kaniko
    build:
      artifacts:
      -  image: aisuko/skaffold
         kaniko:
           image: gcr.io/kaniko-project/executor:latest
           buildArgs:
             cache: true
             single-snapshot: true
      # insecureRegistries: [""]
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.FOO}}"
      cluster:
        pullSecretName: regcred
        namespace: default
        dockerConfig:
          path: /Users/bowen/.docker/config.json
          secretName: auth2
    test:
    -  image: "aisuko/skaffold:v2"
       structureTests:
       -  ./test/*

  - name: test
    test:
    -  image: aisuko/skaffold:v1
       structureTests:
       -  ./test/*

  - name: deploy-helm
    deploy:
      helm:
        releases:
          - name: skaff
            chartPath: skaff
            namespace: skaffo
            wait: false
            recreatePods: true
            skipBuildDependencies: false
            useHelmSecrets: false
            packaged:
              version: 0.2.0
              appVersion: "2.0"
            valuesFiles: [./values.yaml]
            

  - name: deploy-kustomize
    deploy:
      kustomize:
        path: kustom/overlays/staging/
        flags:
          global: []
          apply: []
          delete: []
