apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    params:
    - name: pathToDockerFile
      description: The path to the dockerfile to build
      default: ./Dockerfile

    resources:
    - name: docker-source
      type: git

  outputs:
    resources:
    - name: builtImage
      type: image
  steps:
  - name: build-and-push
    workingdir: /workspace/source
    image: gcr.io/kaniko-project/executor:latest
      
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
      
    command:
    - /kaniko/executor
    - --dockerfile=${inputs.params.pathToDockerFile}
    - --destination=${outputs.resources.builtImage.url}
